// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("Content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("CourseId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("ProfessorId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Announcement", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Dobrodošli na kolegij Matan2",
                            CourseId = 3,
                            CreatedAt = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProfessorId = 9,
                            Title = "Dobrodošli"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Prvi kolokvij održat će se sljedeći tjedan.",
                            CourseId = 2,
                            CreatedAt = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProfessorId = 8,
                            Title = "Kolokvij"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Objavljena je prva zadaća.",
                            CourseId = 3,
                            CreatedAt = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProfessorId = 9,
                            Title = "Zadaća"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Sljedeće predavanje je online.",
                            CourseId = 4,
                            CreatedAt = new DateTime(2024, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProfessorId = 10,
                            Title = "Predavanje"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Dodani su novi materijali.",
                            CourseId = 5,
                            CreatedAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProfessorId = 11,
                            Title = "Materijali"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("ProfessorId");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Course", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Matematika",
                            ProfessorId = 7
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hrvatski jezik",
                            ProfessorId = 8
                        },
                        new
                        {
                            Id = 3,
                            Name = "Matematička analiza 2",
                            ProfessorId = 9
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vještine komuniciranja",
                            ProfessorId = 10
                        },
                        new
                        {
                            Id = 5,
                            Name = "Glazbena kultura",
                            ProfessorId = 11
                        });
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentId");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("CourseId");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollment", "public");

                    b.HasData(
                        new
                        {
                            StudentId = 2,
                            CourseId = 1,
                            Id = 1
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 1,
                            Id = 2
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 2,
                            Id = 3
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 2,
                            Id = 4
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 3,
                            Id = 5
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 3,
                            Id = 6
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 4,
                            Id = 7
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 5,
                            Id = 8
                        });
                });

            modelBuilder.Entity("Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("CourseId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("ProfessorId");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Material", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Algebarski izrazi",
                            ProfessorId = 7,
                            Url = "https://example.com/algebarskiizrazi"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lovac u zitu",
                            ProfessorId = 8,
                            Url = "https://example.com/lovacuzitu"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            CreatedAt = new DateTime(2024, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Diferencijalne jednadzbe",
                            ProfessorId = 9,
                            Url = "https://example.com/difjedn"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            CreatedAt = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kako komunicirati",
                            ProfessorId = 10,
                            Url = "https://example.com/komuniciranje"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            CreatedAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Klasicizam",
                            ProfessorId = 11,
                            Url = "https://example.com/klasicizam"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("Content");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("ReceiverId");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("SenderId");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("SentAt");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("PrivateMessage", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Profesorice, imam pitanje.",
                            ReceiverId = 7,
                            SenderId = 2,
                            SentAt = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Naravno, pitaj.",
                            ReceiverId = 2,
                            SenderId = 7,
                            SentAt = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Kad je kolokvij",
                            ReceiverId = 8,
                            SenderId = 3,
                            SentAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Sljedeći tjedan.",
                            ReceiverId = 3,
                            SenderId = 8,
                            SentAt = new DateTime(2024, 10, 2, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Domaći mi nije jasnan",
                            ReceiverId = 9,
                            SenderId = 4,
                            SentAt = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Objasnit ću na predavanju.",
                            ReceiverId = 4,
                            SenderId = 9,
                            SentAt = new DateTime(2024, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Content = "Ima li dodatnih bodova?",
                            ReceiverId = 10,
                            SenderId = 5,
                            SentAt = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Vidit ćemo.",
                            ReceiverId = 5,
                            SenderId = 10,
                            SentAt = new DateTime(2024, 10, 4, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Content = "Imam problema s materijalima.",
                            ReceiverId = 11,
                            SenderId = 6,
                            SentAt = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Content = "Pošalji screen.",
                            ReceiverId = 6,
                            SenderId = 11,
                            SentAt = new DateTime(2024, 10, 5, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Surname");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mia.barada@gmail.com",
                            Name = "Mia",
                            PasswordHash = "12345678",
                            Role = "Admin",
                            Surname = "Barada"
                        },
                        new
                        {
                            Id = 2,
                            Email = "andrea.barada@gmail.com",
                            Name = "Andrea",
                            PasswordHash = "87654321",
                            Role = "Student",
                            Surname = "Barada"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sara.cigler@gmail.com",
                            Name = "Sara",
                            PasswordHash = "11223344",
                            Role = "Student",
                            Surname = "Cigler"
                        },
                        new
                        {
                            Id = 4,
                            Email = "daria.pazanin@gmail.com",
                            Name = "Daria",
                            PasswordHash = "44332211",
                            Role = "Student",
                            Surname = "Pazanin"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ana.bartulovic@gmail.com",
                            Name = "Ana",
                            PasswordHash = "12121212",
                            Role = "Student",
                            Surname = "Bartulovic"
                        },
                        new
                        {
                            Id = 6,
                            Email = "lea.zebic@gmail.com",
                            Name = "Lea",
                            PasswordHash = "34343434",
                            Role = "Student",
                            Surname = "Zebic"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mia.milun@gmail.com",
                            Name = "Mia",
                            PasswordHash = "13131313",
                            Role = "Profesor",
                            Surname = "Milun"
                        },
                        new
                        {
                            Id = 8,
                            Email = "maja.milanovic@gmail.com",
                            Name = "Maja",
                            PasswordHash = "14141414",
                            Role = "Profesor",
                            Surname = "Milanovic"
                        },
                        new
                        {
                            Id = 9,
                            Email = "tomislav.buric@gmail.com",
                            Name = "Tomislav",
                            PasswordHash = "232323",
                            Role = "Profesor",
                            Surname = "Buric"
                        },
                        new
                        {
                            Id = 10,
                            Email = "predrag.pale@gmail.com",
                            Name = "Predrag",
                            PasswordHash = "24242424",
                            Role = "Profesor",
                            Surname = "Pale"
                        },
                        new
                        {
                            Id = 11,
                            Email = "ines.kezic@gmail.com",
                            Name = "Ines",
                            PasswordHash = "32323232",
                            Role = "Profesor",
                            Surname = "Kezic"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Announcement", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.HasOne("Domain.Entities.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.Material", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Domain.Entities.PrivateMessage", b =>
                {
                    b.HasOne("Domain.Entities.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
